### ISSUE TITLE
Question about reading directories

### ISSUE THREAD

**Issue by mrmlnc** [BigstickCarpet/readdir-enhanced#6]
Hello, @BigstickCarpet,

Firstly, very thanks you for this package. This package works faster analogues and covers all my needs. 🌮

Do you not think about how to prevent the reading of the directory, if it has been filtered? I'm not mean filter of results, I talk about skip the contents of the directory, if it has been filtered.

For example,

**filter**

```js
function filter(stat) {
  console.log('stat: ', stat.path);
  if (stat.isDirectory() && stat.path === 'a') {
    console.log('Hello from the "a/" directory!');
    return false;
  }
  return true;
}
```

**current behaviour**

```
stat:  a
Hello from the "a/" directory!
stat:  a.txt
stat:  a\b                  // <--- but "a" is filtered
stat:  a\b\b.no-txt    // <--- but "a" is filtered
stat:  a\b\c               // <--- but "a" is filtered
stat:  a\b\c\d           // <--- but "a" is filtered
stat:  a\b\c\d\e.txt   // <--- but "a" is filtered
```

**expected behaviour**

```
stat:  a
Hello from the "a/" directory!
stat:  a.txt
```

I ask because this may severely degrade performance on very large projects.

**Comment by BigstickCarpet** [comment]
That seems like a totally valid expectation.  I'll look into the code when I get a chance and see why it doesn't do this.  Maybe there's a reason for the current behavior, or maybe it's just something I overlooked.  Either way, I'll let you know.

**Comment by mrmlnc** [comment]
Small clarification:

```js
re.async.stat('./fixtures', {
	deep: true,
	filter: (stat) => {
		console.log('stat: ', stat.path);
		if (stat.isDirectory() && stat.path === 'a') {
			console.log('Hello from the "a/" directory!');
			return false;
		}

		return true;
	}
}, (err, res) => {
	console.log('---', res.map((x) => x.path));
});
```

**Comment by mrmlnc** [comment]
Well, problem here: 

[lib/directory-reader.js#L165-L194](https://github.com/BigstickCarpet/readdir-enhanced/blob/master/lib/directory-reader.js#L165-L194)

Should be:

```js
  // Get the fs.Stats object for this path
  stat(options.facade.fs, fullPath, function (err, stats) {
    if (err) {
      reader.emit('error', err);
      return done();
    }

    // Determine whether this item matches the filter criteria
    stats.path = itemPath;
    if (!reader.filter(stats, posixPath)) {
      return done();
    }

    if (recurse && stats.isDirectory()) {
      // Add this subdirectory to the queue
      reader.queue.push({
        path: fullPath,
        basePath: itemPath + options.sep,
        posixBasePath: posixPath + '/',
        depth: dir.depth + 1,
      });
    }

    reader.pushOrBuffer({
      data: options.stats ? stats : itemPath,
      file: stats.isFile(),
      directory: stats.isDirectory(),
      symlink: stats.isSymbolicLink(),
    });

    done();
  });
```

But it breaks `should return filtered deep contents` test, because we skip nested directory by condition on first stage.

**Comment by mrmlnc** [comment]
Fiendly ping to @BigstickCarpet 🏓

**Comment by BigstickCarpet** [comment]
Sorry, I've been super busy for the past several weeks and haven't had any spare time to look into this.  Maybe next week, in the lull between Christmas and New Years.

**Comment by mrmlnc** [comment]
Well, just my 2 cents for this case. It works fine with this code [directory-reader.js#L135](https://github.com/BigstickCarpet/readdir-enhanced/blob/master/lib/directory-reader.js#L135):

```js
DirectoryReader.prototype.processItem = function processItem (dir, item, done) {
  // ...
  stat(options.facade.fs, fullPath, function (err, stats) {
    if (err) {
      reader.emit('error', err);
      return done();
    }

    // Determine whether this item matches the filter criteria
    stats.path = itemPath;
    if (!reader.filter(stats, posixPath)) {
      return done();
    }

    if (recurse && stats.isDirectory()) {
      // Add this subdirectory to the queue
      reader.queue.push({
        path: fullPath,
        basePath: itemPath + options.sep,
        posixBasePath: posixPath + '/',
        depth: dir.depth + 1,
      });
    }

    reader.pushOrBuffer({
      data: options.stats ? stats : itemPath,
      file: stats.isFile(),
      directory: stats.isDirectory(),
      symlink: stats.isSymbolicLink(),
    });

    done();
  });
};
```

But it breaks some tests and module behavior. For example, if I set `deep` property as `true` and filter as:

```js
        filter: function (stats) {
          return stats.isFile();
        }
```

I'll never get files from nested directories, because any directory will be skiped by condition.

Theoretically, this can be corrected by using the additional option: could be something like `allowSkipDirectory`.

**Comment by BigstickCarpet** [comment]
Ok, thanks.  I think that's probably acceptable, but I'll need to check how/if this change will affect [chai-fs](https://github.com/chaijs/chai-fs), which uses this module for many of its assertions.  I may need to add an option to control this behavior

**Comment by mrmlnc** [comment]
IMO, after a month I look at this opportunity skeptic. This behavior is always broken for tasks with `deep` option. For example (addition to the previous examples):

  * `**/*.txt` - any nested directory will be skipped (`test/nested/a.txt`).
  * `/a\.txt/` - any nested directory will be skipped (`test/nested/a.txt`).

Well, I would love to hear your thoughts.

**Comment by princed** [comment]
[readdirp](https://github.com/thlorenz/readdirp#options) solves the issue providing separate filters for directories and files. 

(I had to switch from readdirp because it doesn't implement back-pressure)

**Comment by BigstickCarpet** [comment]
Hi @mrmlnc and @princed.  I'm implementing a fix for this issue right now.  Expect it to be released shortly.

I came up with a way to solve the problem without breaking backward-compatibility.  The behavior of the `filter` option will remain unchanged.  But the `deep` option can now be set to a function, glob, or RegExp, which allows you to customize which directories will be crawled.

**Comment by princed** [comment]
Great news and an excellent idea! Can't wait to see in released!

**Comment by BigstickCarpet** [comment]
Done!  Upgrade to v1.5.0 to try-out the [new functionality of the `deep` option](https://github.com/BigstickCarpet/readdir-enhanced#deep)
