### ISSUE TITLE
Ability to use depth in the custom deep function

### ISSUE THREAD

**Issue by mrmlnc** [BigstickCarpet/readdir-enhanced#7]
If we use `deep` option as custom function we cannot control depth. May be we must provide number of depth to function arguments?

For example:

```ts
const options = {
	deep: (entry: IReaddirEntry, depth: number) => ...
};
```

**Comment by BigstickCarpet** [comment]
Good point.  I'll plan to add a `.depth` property to the `Stats` object that's passed to the function.

For the time being though, you can determine the depth by the number of path separators in the `.path` property.  Like this:

```javascript
var depth = stats.path.split('/').length;
```

**Comment by mrmlnc** [comment]
Yeap, thanks for your answer! Now I use similar code snippet, but will be cool if this property will be available in the Stats object.

_Sent from my Xiaomi Redmi Note 4X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
