### ISSUE TITLE
Move internalOptions.facade to public api

### ISSUE THREAD

**Issue by mrmlnc** [BigstickCarpet/readdir-enhanced#9]
Well, I want to use your package with my own FS facade functions, for example, [scandir-native](https://github.com/mrmlnc/scandir-native). It seems that it would be useful not only me. For example, if you want to use this package for walk directories in the remote drive.

**Comment by BigstickCarpet** [comment]
👍  Sounds like a good idea to me.  Feel free to submit a PR if you want.  Or I'll get to it whenever my schedule allows
